name: Chengla BaeMin

on:
  repository_dispatch:
    types: [run-chengla-baemin]  # 트리거 타입 정의

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Decode and Save Service Account JSON
        env:
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > /tmp/keyfile.json

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          CHENGLA_BAEMIN_ID: ${{ secrets.CHENGLA_BAEMIN_ID }}
          CHENGLA_BAEMIN_PW: ${{ secrets.CHENGLA_BAEMIN_PW }}
        run: |
          python 2-chengla-baemin-auto.py
