name: Chengla Baemin

on:
  workflow_dispatch:

jobs:
  run-baemin-script:
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
        shell: cmd

      - name: Run Baemin Auto Script
        run: python 2-chengla-baemin-auto.py
        env:
          CHENGLA_BAEMIN_ID: ${{ secrets.CHENGLA_BAEMIN_ID }}
          CHENGLA_BAEMIN_PW: ${{ secrets.CHENGLA_BAEMIN_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
          PYTHONIOENCODING: utf-8
