name: BaeminAutoSelfHosted

on:
  workflow_dispatch:

jobs:
  run-baemin-script:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # etc...

      - name: Run Baemin Auto Script
        run: |
          python 2-chengla-baemin-auto.py
        env:
          CHENGLA_BAEMIN_ID: ${{ secrets.CHENGLA_BAEMIN_ID }}
          CHENGLA_BAEMIN_PW: ${{ secrets.CHENGLA_BAEMIN_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}

      - name: Upload screenshot artifact
        if: always()  # 스크립트 실패/성공 모두 업로드하고 싶으면 always()
        uses: actions/upload-artifact@v3
        with:
          name: baemin-screenshot
          path: |
            login_timeout.png
            login_timeout.html
