name: Chengla Baemin

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정에 실행
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CHENGLA_BAEMIN_ID: ${{ secrets.CHENGLA_BAEMIN_ID }}
      CHENGLA_BAEMIN_PW: ${{ secrets.CHENGLA_BAEMIN_PW }}
      SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python 2-chengla-baemin-auto.py

      - name: Upload Screenshots and HTML
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-files
          path: |
            before_login.png
            after_login_timeout.png
            after_login_exception.png
            after_login_error.png
            before_login.html
            after_login_timeout.html
            after_login_exception.html
            after_login_error.html
