name: Mugung Baemin Auto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시에 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "CHENGLA_BAEMIN_ID=${{ secrets.CHENGLA_BAEMIN_ID }}" >> $GITHUB_ENV
          echo "CHENGLA_BAEMIN_PW=${{ secrets.CHENGLA_BAEMIN_PW }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT_JSON_BASE64=${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" >> $GITHUB_ENV

      - name: Run Python script
        run: |
          python 2-chengla-baemin-auto.py
        env:
          SERVICE_ACCOUNT_JSON_BASE64: ${{ env.SERVICE_ACCOUNT_JSON_BASE64 }}

