name: Chengla Baemin

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시에 실행

jobs:
  build:
    runs-on: self-hosted  # self-hosted runner 사용
    # 특정 태그를 사용하는 경우 아래처럼 지정
    # runs-on: [self-hosted, google-cloud]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "CHENGLA_BAEMIN_ID=${{ secrets.CHENGLA_BAEMIN_ID }}" >> $GITHUB_ENV
          echo "CHENGLA_BAEMIN_PW=${{ secrets.CHENGLA_BAEMIN_PW }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT_JSON_BASE64=${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" >> $GITHUB_ENV

      - name: Run Python script
        run: |
          python 2-chengla-baemin-auto.py
        env:
          CHENGLA_BAEMIN_ID: ${{ env.CHENGLA_BAEMIN_ID }}
          CHENGLA_BAEMIN_PW: ${{ env.CHENGLA_BAEMIN_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ env.SERVICE_ACCOUNT_JSON_BASE64 }}

      - name: Upload Logs and Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: debug-artifacts
          path: |
            script.log
            *.png
            *.html
