name: BaeminAutoSelfHosted

on:
  workflow_dispatch:

jobs:
  run-baemin-script:
    # 기존 'runs-on: ubuntu-latest' 대신:
    runs-on: self-hosted
    # 또는 'runs-on: [self-hosted, mylabel]' if you added a custom label

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Chrome 설치
          sudo apt-get install -y wget gnupg2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          # 의존 패키지
          sudo apt-get install -y libnss3 libxss1 libappindicator3-1 libgbm1 libgtk-3-0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Baemin Auto Script
        run: python 2-chengla-baemin-auto.py
        env:
          CHENGLA_BAEMIN_ID: ${{ secrets.CHENGLA_BAEMIN_ID }}
          CHENGLA_BAEMIN_PW: ${{ secrets.CHENGLA_BAEMIN_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}

