name: Easy Pos Auto

on:
  schedule:
    # KST 12:00부터 23:30까지 (UTC 03:00 ~ 14:30) 매 30분마다 실행
    - cron: "0,30 3-14 * * *"
    # KST 23:30부터 23:50까지 (UTC 14:30 ~ 14:50) 매 10분마다 실행
    - cron: "30,40,50 14 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Decode JSON Key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > /tmp/keyfile.json

      # 두 번째 스크립트 실행 (예: 청라)
      - name: Run Chengla script
        env:
          CHENGLA_EASY_POS_ID: ${{ secrets.CHENGLA_EASY_POS_ID }}
          CHENGLA_EASY_POS_PW: ${{ secrets.CHENGLA_EASY_POS_PW }}
        run: |
          python 2-chengla-easy-pos-auto.py
