name: Naver Place Checker

on:
  schedule:
    - cron: "0 3 * * *"  # 매일 03:00 UTC -> 12:00pm
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Decode JSON Key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}" | base64 --decode > /tmp/keyfile.json

      # 첫 번째 스크립트 실행 (예: 송도)
      - name: Run Songdo script
        run: |
          python 1-songdo-naver-place-checker.py

      # 두 번째 스크립트 실행 (예: 청라)
      - name: Run Chengla script
        run: |
          python 2-chengla-naver-place-checker.py
