name: Songdo Dodo

on:
  repository_dispatch:
    types: [run-songdo-dodo]  # 원하는 이벤트 타입
  workflow_dispatch:  # ← 수동으로도 실행할 수 있게 추가

jobs:
  run-script:
    runs-on: self-hosted  # 로컬/개인 PC Runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
        shell: cmd  # Windows라면 cmd, Linux면 생략가능

      - name: Run Dodo Auto Script
        run: python 1-songdo-dodo-auto.py
        shell: cmd
        env:
          SONGDO_DODO_ID: ${{ secrets.SONGDO_DODO_ID }}
          SONGDO_DODO_PW: ${{ secrets.SONGDO_DODO_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
          PYTHONIOENCODING: utf-8
