name: Songdo Baemin

on:
  repository_dispatch:
    types: [run-songdo-baemin]  # 원하는 이벤트 타입
  workflow_dispatch:  # ← 수동으로도 실행할 수 있게 추가

jobs:
  run-script:
    runs-on: ubuntu-latest  # 로컬/개인 PC Runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Baemin Auto Script
        run: python 1-songdo-baemin-auto.py
        env:
          SONGDO_BAEMIN_ID: ${{ secrets.SONGDO_BAEMIN_ID }}
          SONGDO_BAEMIN_PW: ${{ secrets.SONGDO_BAEMIN_PW }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON_BASE64 }}
        
